services:
  nextjs-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add other environment variables here if needed
      # - NEXT_PUBLIC_API_URL=https://api.example.com
    volumes:
      - ./public:/app/public:ro
      # Uncomment if you need hot-reload in development:
      # - .:/app
      # - /app/node_modules
    restart: unless-stopped
    networks:
      - portfolio-network

  # Uncomment if you need a reverse proxy like Nginx
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./public:/usr/share/nginx/html:ro
  #   depends_on:
  #     - nextjs-portfolio
  #   networks:
  #     - portfolio-network

networks:
  portfolio-network:
    driver: bridge